version: '3'

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:

services:

  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data{1...4}
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
      PGDATA: /database
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  concourse-web:
    image: concourse/concourse
    command: web
    depends_on: [concourse-db, minio]
    ports: ["8080:8080"]
    volumes: ["/etc/concourse:/etc/concourse"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: arcas:arcas
      CONCOURSE_MAIN_TEAM_LOCAL_USER: arcas
      CONCOURSE_SESSION_SIGNING_KEY: /etc/concourse/session_signing_key
      CONCOURSE_TSA_HOST_KEY: /etc/concourse/tsa_host_key
      CONCOURSE_TSA_AUTHORIZED_KEYS: /etc/concourse/authorized_worker_keys
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      CONCOURSE_CLUSTER_NAME: tutorial
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  concourse-worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [concourse-web]
    stop_signal: SIGUSR2
    volumes: ["/etc/concourse:/etc/concourse","/opt/concourse/worker:/opt/concourse/worker"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222
      CONCOURSE_TSA_PUBLIC_KEY: /etc/concourse/tsa_host_key.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: /etc/concourse/worker_key
      CONCOURSE_GARDEN_DNS_SERVER: "8.8.8.8"
      CONCOURSE_GARDEN_ALLOW_HOST_ACCESS: "true"
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
      CONCOURSE_BIND_PORT: 80
      CONCOURSE_WORK_DIR: /opt/concourse/worker
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
